version: '3.1'

services:
  pg:
    image: postgres:12-alpine
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_PASSWORD: rblog
      POSTGRES_DB: rblog
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rblog@rblog.com
      PGADMIN_DEFAULT_PASSWORD: rblog
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
